Fix macOS builds
Fixes `cargo build` on macOS. Before, the python binding build was
failing to link against libpython, giving errors like this:
```
error: linking with `cc` failed: exit status: 1
  ...
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: Undefined symbols for architecture x86_64:
            "_PyBaseObject_Type", referenced from:
                _$LT$pyo3..types..any..PyAny$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::h4422157908a511b6 in ironcalc.5yhisif8weqj2f2maodskna55.0ysvvdb.rcgu.o
	    ...
            "_PyBool_Type", referenced from:
                pyo3_ffi::object::Py_SIZE::h7560f69b62aca995 in libpyo3-02c35b5d6eece54a.rlib[10](pyo3-02c35b5d6eece54a.pyo3.110ae39358168073-cgu.07.rcgu.o)
```

The fix is found in pyo3's docs here: https://pyo3.rs/v0.14.5/building_and_distribution.html#macos

I've opted to use the `build.rs` approach here so that the config
changes are scoped tightly to the python bindings, rather than passing
as flags in the root cargo config.